version: '3.8'

services:
  server1:
    build: ./server
    environment:
      - SERVER_ID=1
    networks:
      - app-network

  server2:
    build: ./server
    environment:
      - SERVER_ID=2
    networks:
      - app-network

  server3:
    build: ./server
    environment:
      - SERVER_ID=3
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - server1
      - server2
      - server3

networks:
  app-network:
    driver: bridge
